### ISSUE TITLE
undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by tmaier** [ErwinM/acts_as_tenant#62]
I get the following error message in my tests since upgrading from v0.3.1 to v0.3.3

> undefined method `id' for nil:NilClass

I guess the fault lies in https://github.com/ErwinM/acts_as_tenant/blob/master/lib/acts_as_tenant/model_extensions.rb#L97

``` ruby
define_method "#{ActsAsTenant.tenant_klass.to_s}" do
  return ActsAsTenant.current_tenant if send(fkey) == ActsAsTenant.current_tenant.id
  super()
end
```

`ActsAsTenant.current_tenant` could be `nil`

I would have another request to you which is not worth an issue: Could you please run `git push origin --tags`. I would like to use the following URL to check for changes on gems I depend on: https://github.com/ErwinM/acts_as_tenant/compare/v0.3.1...v0.3.3
